name: Deploy Infraestructura AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar el código del repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configurar credenciales AWS (Las toma de los Secretos que creaste)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 4. Iniciar Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Aplicar cambios (Automáticamente al hacer push a main)
    - name: Terraform Apply
      run: terraform apply -auto-approve