name: Deploy Infraestructura AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar el código del repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configurar credenciales AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 3. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 4. Iniciar Terraform
    - name: Terraform Init
      run: terraform init

    # 5. Aplicar cambios
    - name: Terraform Apply
      # ESTA ES LA SECCIÓN QUE FALTABA:
      env:
        # Terraform busca variables que empiecen con TF_VAR_
        TF_VAR_gemini_api_key: ${{ secrets.TF_VAR_GEMINI_API_KEY }}
        TF_VAR_alert_email: ${{ secrets.TF_VAR_ALERT_EMAIL }}
      run: terraform apply -auto-approve